apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: argotest
  name: argotest
spec:
  containers:
  - image: {{ .Values.image }}
    name: {{ .Values.name }}
  restartPolicy: Always

